;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	god-mode-self-insert
	kill-region-smart
	mark-toggle
	org-beginning-of-line
	org-self-insert-command
	undefined
	wrath
	))

(setq mc/cmds-to-run-once
      '(
	swiper-isearch
	swiper-mc
	))
